GitHub-Actions: Check if version is inside CHANGELOG.md (+ Updated CHANGELOG.md) (#19)
* Check if version is inside CHANGELOG.md
* Update CHANGELOG.md

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -20,7 +20,7 @@ jobs:
         with:
           java-version: 1.8
       - name: Extract version from pom.xml and compare to docs/version.txt
-        id: version_diff
+        id: version_diff  # Outputs 'same' or 'diff'
         run: mkdir -p docs && echo $(grep --max-count=1 '<version>' pom.xml | awk -F '>' '{ print $2 }' | awk -F '<' '{ print $1 }') >> docs/version_new.txt && diff -q --ignore-space-change --strip-trailing-cr --ignore-blank-lines docs/version.txt docs/version_new.txt 2>&1 && echo "##[set-output name=result;]same" || echo "##[set-output name=result;]diff"
       - name: Check if extracted version matches docs/version.txt
         if: ${{ steps.version_diff.outputs.result == 'diff' }}
@@ -30,9 +30,23 @@ jobs:
           check_for_duplicate_msg: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check if version from docs/version.txt is inside CHANGELOG.md
+        id: inside_changelog  # Outputs 'yes' or 'no'
+        run: verTxt=$(cat docs/version.txt) && grep -q "## Version ${verTxt}" CHANGELOG.md && echo "##[set-output name=result;]yes" || echo "##[set-output name=result;]no"
+      - name: Check if extracted version matches docs/version.txt
+        if: ${{ steps.inside_changelog.outputs.result == 'no' }}
+        uses: unsplash/comment-on-pr@master
+        with:
+          msg: "`CHANGELOG.md` is missing changes for version in `docs/version.txt`!"
+          check_for_duplicate_msg: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Fail Action when versions (from above) are not the same
         if: ${{ steps.version_diff.outputs.result == 'diff' }}
         run: echo "Versions in pom.xml and docs/version.txt are not the same!" && exit -1
+      - name: Fail Action when docs/version.txt not inside CHANGELOG.md
+        if: ${{ steps.inside_changelog.outputs.result == 'no' }}
+        run: echo "CHANGELOG.md is missing changes for version in docs/version.txt!" && exit -1
 
   build:
     runs-on: ubuntu-latest
